//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.Models.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsLayoutsLink
    {
        public int ID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Layout { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual ProjectLayout_Collection ProjectLayout_Collection { get; set; }
    }
}
