//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.Models.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_detail = new HashSet<Product_detail>();
            this.ProductsLayoutsLinks = new HashSet<ProductsLayoutsLink>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<int> Product_type_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> Product_typeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> featured { get; set; }
        public string image { get; set; }
        public string excerpt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_detail> Product_detail { get; set; }
        public virtual Product_type Product_type { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsLayoutsLink> ProductsLayoutsLinks { get; set; }
    }
}
