//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Category_detail = new HashSet<Category_detail>();
            this.Category1 = new HashSet<Category>();
            this.Products = new HashSet<Product>();
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> Category_type_id { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public Nullable<int> Category_typeId { get; set; }
    
        public virtual Category_type Category_type { get; set; }
        public virtual ICollection<Category_detail> Category_detail { get; set; }
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
