
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Homeclick.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Product_type
{

    public Product_type()
    {

        this.Products = new HashSet<Product>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string caption { get; set; }



    public virtual ICollection<Product> Products { get; set; }

}

}
