//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_detail
    {
        public int Id { get; set; }
        public Nullable<int> ProductsId { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string caption { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string type { get; set; }
        public Nullable<int> typeEnum { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
