
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Homeclick.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectLayout_Collection
{

    public ProjectLayout_Collection()
    {

        this.Products = new HashSet<Product>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public string HtmlContent { get; set; }

    public string Area { get; set; }

    public Nullable<int> LayoutId { get; set; }

    public Nullable<bool> LockedOut { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<int> UpdatedBy { get; set; }



    public virtual ICollection<Product> Products { get; set; }

    public virtual ProjectItem Layout { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual User UpdatedByUser { get; set; }

}

}
