
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Homeclick.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Room
{

    public Room()
    {

        this.Canvas = new HashSet<Canva>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public Nullable<int> floor_id { get; set; }

    public string coordinates { get; set; }

    public string canvas_data { get; set; }

    public Nullable<int> FloorId { get; set; }



    public virtual ICollection<Canva> Canvas { get; set; }

    public virtual Floor Floor { get; set; }

}

}
