//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Canvas = new HashSet<Canva>();
            this.Carts = new HashSet<Cart>();
            this.Customers = new HashSet<Customer>();
            this.Posts = new HashSet<Post>();
            this.Products = new HashSet<Product>();
            this.Wishlists = new HashSet<Wishlist>();
            this.CustomSecurityRoles = new HashSet<CustomSecurityRole>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ChangePasswordOnFirstLogon { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string StoredPassword { get; set; }
    
        public virtual ICollection<Canva> Canvas { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Wishlist> Wishlists { get; set; }
        public virtual ICollection<CustomSecurityRole> CustomSecurityRoles { get; set; }

        internal void Add(string p, Customer customer)
        {
            throw new NotImplementedException();
        }
    }
}
