//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public Wishlist()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string title { get; set; }
        public string created_date { get; set; }
        public string description { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
