//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    using DevExpress.Xpo;
    using System.ComponentModel.DataAnnotations.Schema;
    using DevExpress.ExpressApp.ConditionalAppearance;
    using DevExpress.ExpressApp.Editors;
    using DevExpress.Persistent.Base;
    using DevExpress.ExpressApp.Model;
    public partial class Canva: XPLiteObject
    {
        private int _id;
    	[DevExpress.Xpo.Key(true)]
    	[Required]
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private int _room_id;
    	[Required]
    	public int room_id 
    	{ 
    		get { return _room_id; } 
    		set
    		{
    			if (value != _room_id) {
    				_room_id = value;
    				 Onroom_idChanged();
    			}
    		} 
    	}
    	partial void Onroom_idChanged(); 
    
        private Nullable<int> _user_id;
    	public Nullable<int> user_id 
    	{ 
    		get { return _user_id; } 
    		set
    		{
    			if (value != _user_id) {
    				_user_id = value;
    				 Onuser_idChanged();
    			}
    		} 
    	}
    	partial void Onuser_idChanged(); 
    
        private string _json_data;
    	public string json_data 
    	{ 
    		get { return _json_data; } 
    		set
    		{
    			if (value != _json_data) {
    				_json_data = value;
    				 Onjson_dataChanged();
    			}
    		} 
    	}
    	partial void Onjson_dataChanged(); 
    
        private Nullable<int> _cart_id;
    	public Nullable<int> cart_id 
    	{ 
    		get { return _cart_id; } 
    		set
    		{
    			if (value != _cart_id) {
    				_cart_id = value;
    				 Oncart_idChanged();
    			}
    		} 
    	}
    	partial void Oncart_idChanged(); 
    
    
        private Room _RoomId;
    	[ImmediatePostData]
    	[Association(@"CanvasRoomsReferences", typeof(Room))]
    	public  Room RoomId { get {return _RoomId;} set{ SetPropertyValue<Room>("RoomId", ref _RoomId, value); } }
    
        private Cart _CartId;
    	[ImmediatePostData]
    	[Association(@"CartsCanvasReferences", typeof(Cart))]
    	public  Cart CartId { get {return _CartId;} set{ SetPropertyValue<Cart>("CartId", ref _CartId, value); } }
    
        private User _UserId;
    	[ImmediatePostData]
    	[Association(@"UserCanvasReferences", typeof(User))]
    	public  User UserId { get {return _UserId;} set{ SetPropertyValue<User>("UserId", ref _UserId, value); } }
    
    }
}
