//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    using DevExpress.Xpo;
    using System.ComponentModel.DataAnnotations.Schema;
    using DevExpress.ExpressApp.ConditionalAppearance;
    using DevExpress.ExpressApp.Editors;
    using DevExpress.Persistent.Base;
    using DevExpress.ExpressApp.Model;
    public partial class Customer: XPLiteObject
    {
        private int _id;
    	[DevExpress.Xpo.Key(true)]
    	[Required]
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private string _first_name;
    	[Required]
    	public string first_name 
    	{ 
    		get { return _first_name; } 
    		set
    		{
    			if (value != _first_name) {
    				_first_name = value;
    				 Onfirst_nameChanged();
    			}
    		} 
    	}
    	partial void Onfirst_nameChanged(); 
    
        private string _middle_name;
    	[Required]
    	public string middle_name 
    	{ 
    		get { return _middle_name; } 
    		set
    		{
    			if (value != _middle_name) {
    				_middle_name = value;
    				 Onmiddle_nameChanged();
    			}
    		} 
    	}
    	partial void Onmiddle_nameChanged(); 
    
        private string _last_name;
    	[Required]
    	public string last_name 
    	{ 
    		get { return _last_name; } 
    		set
    		{
    			if (value != _last_name) {
    				_last_name = value;
    				 Onlast_nameChanged();
    			}
    		} 
    	}
    	partial void Onlast_nameChanged(); 
    
        private string _address;
    	[Required]
    	public string address 
    	{ 
    		get { return _address; } 
    		set
    		{
    			if (value != _address) {
    				_address = value;
    				 OnaddressChanged();
    			}
    		} 
    	}
    	partial void OnaddressChanged(); 
    
        private int _customer_type_id;
    	[Required]
    	public int customer_type_id 
    	{ 
    		get { return _customer_type_id; } 
    		set
    		{
    			if (value != _customer_type_id) {
    				_customer_type_id = value;
    				 Oncustomer_type_idChanged();
    			}
    		} 
    	}
    	partial void Oncustomer_type_idChanged(); 
    
        private string _phone;
    	[Required]
    	public string phone 
    	{ 
    		get { return _phone; } 
    		set
    		{
    			if (value != _phone) {
    				_phone = value;
    				 OnphoneChanged();
    			}
    		} 
    	}
    	partial void OnphoneChanged(); 
    
        private int _city_id;
    	[Required]
    	public int city_id 
    	{ 
    		get { return _city_id; } 
    		set
    		{
    			if (value != _city_id) {
    				_city_id = value;
    				 Oncity_idChanged();
    			}
    		} 
    	}
    	partial void Oncity_idChanged(); 
    
    
        private User _UserId;
    	[ImmediatePostData]
    	//One to One: From 'Customer' to 'User'
    	public  User UserId { 
    		get {return _UserId;}
    		set{ SetPropertyValue<User>("UserId", ref _UserId, value); OnChanged("UserId"); }
    	 }
    
        private Customer_type _Customer_typeId;
    	[ImmediatePostData]
    	[Association(@"CustomerCustomer_typeReferences", typeof(Customer_type))]
    	public  Customer_type Customer_typeId { get {return _Customer_typeId;} set{ SetPropertyValue<Customer_type>("Customer_typeId", ref _Customer_typeId, value); } }
    
        private City _CityId;
    	[ImmediatePostData]
    	[Association(@"CustomerCityReferences", typeof(City))]
    	public  City CityId { get {return _CityId;} set{ SetPropertyValue<City>("CityId", ref _CityId, value); } }
    
    }
}
