//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    using DevExpress.Xpo;
    using System.ComponentModel.DataAnnotations.Schema;
    using DevExpress.ExpressApp.ConditionalAppearance;
    using DevExpress.ExpressApp.Editors;
    using DevExpress.Persistent.Base;
    using DevExpress.ExpressApp.Model;
    public partial class Department: XPLiteObject
    {
    	//VNB: Department
        public Department()
        {
            //VNB disable: this.ChildrenDepartment = new List<Department>();
            //VNB disable: this.Floors = new List<Floor>();
        }
    
        private int _id;
    	[DevExpress.Xpo.Key(true)]
    	[Required]
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private string _name;
    	[Required]
    	public string name 
    	{ 
    		get { return _name; } 
    		set
    		{
    			if (value != _name) {
    				_name = value;
    				 OnnameChanged();
    			}
    		} 
    	}
    	partial void OnnameChanged(); 
    
        private string _address;
    	public string address 
    	{ 
    		get { return _address; } 
    		set
    		{
    			if (value != _address) {
    				_address = value;
    				 OnaddressChanged();
    			}
    		} 
    	}
    	partial void OnaddressChanged(); 
    
        private string _desciption;
    	public string desciption 
    	{ 
    		get { return _desciption; } 
    		set
    		{
    			if (value != _desciption) {
    				_desciption = value;
    				 OndesciptionChanged();
    			}
    		} 
    	}
    	partial void OndesciptionChanged(); 
    
        private Nullable<int> _parent_id;
    	public Nullable<int> parent_id 
    	{ 
    		get { return _parent_id; } 
    		set
    		{
    			if (value != _parent_id) {
    				_parent_id = value;
    				 Onparent_idChanged();
    			}
    		} 
    	}
    	partial void Onparent_idChanged(); 
    
    
        [Association(@"DepartmentsDepartmentsReferences", typeof(Department))]
    	public  XPCollection<Department> DanhSachChildrenDepartment { get{{ return GetCollection<Department>("DanhSachChildrenDepartment"); }} }
    
        private Department _DepartmentId;
    	[ImmediatePostData]
    	[Association(@"DepartmentsDepartmentsReferences", typeof(Department))]
    	public  Department ParentDepartmentId { get {return _DepartmentId;} set{ SetPropertyValue<Department>("DepartmentId", ref _DepartmentId, value); } }
    
        [Association(@"FloorsDepartmentsReferences", typeof(Floor))]
    	public  XPCollection<Floor> DanhSachFloors { get{{ return GetCollection<Floor>("DanhSachFloors"); }} }
    
    }
}
