//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    using DevExpress.Xpo;
    using System.ComponentModel.DataAnnotations.Schema;
    using DevExpress.ExpressApp.ConditionalAppearance;
    using DevExpress.ExpressApp.Editors;
    using DevExpress.Persistent.Base;
    using DevExpress.ExpressApp.Model;
    public partial class Floor: XPLiteObject
    {
    	//VNB: Floor
        public Floor()
        {
            //VNB disable: this.Rooms = new List<Room>();
        }
    
        private int _id;
    	[DevExpress.Xpo.Key(true)]
    	[Required]
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private string _name;
    	[Required]
    	public string name 
    	{ 
    		get { return _name; } 
    		set
    		{
    			if (value != _name) {
    				_name = value;
    				 OnnameChanged();
    			}
    		} 
    	}
    	partial void OnnameChanged(); 
    
        private string _description;
    	public string description 
    	{ 
    		get { return _description; } 
    		set
    		{
    			if (value != _description) {
    				_description = value;
    				 OndescriptionChanged();
    			}
    		} 
    	}
    	partial void OndescriptionChanged(); 
    
        private int _block_id;
    	[Required]
    	public int block_id 
    	{ 
    		get { return _block_id; } 
    		set
    		{
    			if (value != _block_id) {
    				_block_id = value;
    				 Onblock_idChanged();
    			}
    		} 
    	}
    	partial void Onblock_idChanged(); 
    
        private string _structure_link;
    	[Required]
    	public string structure_link 
    	{ 
    		get { return _structure_link; } 
    		set
    		{
    			if (value != _structure_link) {
    				_structure_link = value;
    				 Onstructure_linkChanged();
    			}
    		} 
    	}
    	partial void Onstructure_linkChanged(); 
    
    
        private Department _DepartmentId;
    	[ImmediatePostData]
    	[Association(@"FloorsDepartmentsReferences", typeof(Department))]
    	public  Department DepartmentId { get {return _DepartmentId;} set{ SetPropertyValue<Department>("DepartmentId", ref _DepartmentId, value); } }
    
        [Association(@"RoomsFloorsReferences", typeof(Room))]
    	public  XPCollection<Room> DanhSachRooms { get{{ return GetCollection<Room>("DanhSachRooms"); }} }
    
    }
}
