//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    using DevExpress.Xpo;
    using System.ComponentModel.DataAnnotations.Schema;
    using DevExpress.ExpressApp.ConditionalAppearance;
    using DevExpress.ExpressApp.Editors;
    using DevExpress.Persistent.Base;
    using DevExpress.ExpressApp.Model;
    public partial class Post_detail: XPLiteObject
    {
        private int _id;
    	[DevExpress.Xpo.Key(true)]
    	[Required]
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private int _post_id;
    	[Required]
    	public int post_id 
    	{ 
    		get { return _post_id; } 
    		set
    		{
    			if (value != _post_id) {
    				_post_id = value;
    				 Onpost_idChanged();
    			}
    		} 
    	}
    	partial void Onpost_idChanged(); 
    
        private string _name;
    	[Required]
    	public string name 
    	{ 
    		get { return _name; } 
    		set
    		{
    			if (value != _name) {
    				_name = value;
    				 OnnameChanged();
    			}
    		} 
    	}
    	partial void OnnameChanged(); 
    
        private string _value;
    	public string value 
    	{ 
    		get { return _value; } 
    		set
    		{
    			if (value != _value) {
    				_value = value;
    				 OnvalueChanged();
    			}
    		} 
    	}
    	partial void OnvalueChanged(); 
    
        private string _caption;
    	public string caption 
    	{ 
    		get { return _caption; } 
    		set
    		{
    			if (value != _caption) {
    				_caption = value;
    				 OncaptionChanged();
    			}
    		} 
    	}
    	partial void OncaptionChanged(); 
    
        private short _type;
    	[Required]
    	public short type 
    	{ 
    		get { return _type; } 
    		set
    		{
    			if (value != _type) {
    				_type = value;
    				 OntypeChanged();
    			}
    		} 
    	}
    	partial void OntypeChanged(); 
    
    
        private Post _PostId;
    	[ImmediatePostData]
    	[Association(@"Post_detailsPostsReferences", typeof(Post))]
    	public  Post PostId { get {return _PostId;} set{ SetPropertyValue<Post>("PostId", ref _PostId, value); } }
    
    }
}
