//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    using DevExpress.Xpo;
    using System.ComponentModel.DataAnnotations.Schema;
    using DevExpress.ExpressApp.ConditionalAppearance;
    using DevExpress.ExpressApp.Editors;
    using DevExpress.Persistent.Base;
    using DevExpress.ExpressApp.Model;
    public partial class Product: XPLiteObject
    {
    	//VNB: Product
        public Product()
        {
            //VNB disable: this.Product_details = new List<Product_detail>();
            //VNB disable: this.Tags = new List<Tag>();
            //VNB disable: this.Wishlists = new List<Wishlist>();
        }
    
        private int _id;
    	[DevExpress.Xpo.Key(true)]
    	[Required]
    	public int Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnIdChanged();
    			}
    		} 
    	}
    	partial void OnIdChanged(); 
    
        private string _name;
    	[Required]
    	public string name 
    	{ 
    		get { return _name; } 
    		set
    		{
    			if (value != _name) {
    				_name = value;
    				 OnnameChanged();
    			}
    		} 
    	}
    	partial void OnnameChanged(); 
    
        private string _content;
    	[Size(SizeAttribute.Unlimited)]
    	public string content 
    	{ 
    		get { return _content; } 
    		set
    		{
    			if (value != _content) {
    				_content = value;
    				 OncontentChanged();
    			}
    		} 
    	}
    	partial void OncontentChanged(); 
    
        private System.DateTime _created_date;
    	[Required]
    	public System.DateTime created_date 
    	{ 
    		get { return _created_date; } 
    		set
    		{
    			if (value != _created_date) {
    				_created_date = value;
    				 Oncreated_dateChanged();
    			}
    		} 
    	}
    	partial void Oncreated_dateChanged(); 
    
        private System.DateTime _updated_date;
    	[Required]
    	public System.DateTime updated_date 
    	{ 
    		get { return _updated_date; } 
    		set
    		{
    			if (value != _updated_date) {
    				_updated_date = value;
    				 Onupdated_dateChanged();
    			}
    		} 
    	}
    	partial void Onupdated_dateChanged(); 
    
        private short _status;
    	[Required]
    	public short status 
    	{ 
    		get { return _status; } 
    		set
    		{
    			if (value != _status) {
    				_status = value;
    				 OnstatusChanged();
    			}
    		} 
    	}
    	partial void OnstatusChanged(); 
    
        private int _product_type_id;
    	[Required]
    	public int Product_type_id 
    	{ 
    		get { return _product_type_id; } 
    		set
    		{
    			if (value != _product_type_id) {
    				_product_type_id = value;
    				 OnProduct_type_idChanged();
    			}
    		} 
    	}
    	partial void OnProduct_type_idChanged(); 
    
        private int _author_id;
    	[Required]
    	public int author_id 
    	{ 
    		get { return _author_id; } 
    		set
    		{
    			if (value != _author_id) {
    				_author_id = value;
    				 Onauthor_idChanged();
    			}
    		} 
    	}
    	partial void Onauthor_idChanged(); 
    
        private bool _featured;
    	[Required]
    	public bool featured 
    	{ 
    		get { return _featured; } 
    		set
    		{
    			if (value != _featured) {
    				_featured = value;
    				 OnfeaturedChanged();
    			}
    		} 
    	}
    	partial void OnfeaturedChanged(); 
    
        private string _excerpt;
    	[Required]
    	[Size(SizeAttribute.Unlimited)]
    	public string excerpt 
    	{ 
    		get { return _excerpt; } 
    		set
    		{
    			if (value != _excerpt) {
    				_excerpt = value;
    				 OnexcerptChanged();
    			}
    		} 
    	}
    	partial void OnexcerptChanged(); 
    
        private string _image;
    	[Required]
    	public string image 
    	{ 
    		get { return _image; } 
    		set
    		{
    			if (value != _image) {
    				_image = value;
    				 OnimageChanged();
    			}
    		} 
    	}
    	partial void OnimageChanged(); 
    
    
        private Product_type _Product_typeId;
    	[ImmediatePostData]
    	[Association(@"ProductsProduct_typesReferences", typeof(Product_type))]
    	public  Product_type Product_typeId { get {return _Product_typeId;} set{ SetPropertyValue<Product_type>("Product_typeId", ref _Product_typeId, value); } }
    
        [Association(@"Product_detailsProductsReferences", typeof(Product_detail))]
    	public  XPCollection<Product_detail> DanhSachProduct_details { get{{ return GetCollection<Product_detail>("DanhSachProduct_details"); }} }
    
        [Association(@"ProductsTagsReferences", typeof(Tag))]
    	public  XPCollection<Tag> DanhSachTags { get{{ return GetCollection<Tag>("DanhSachTags"); }} }
    
        private User _UserId;
    	[ImmediatePostData]
    	[Association(@"UserProductsReferences", typeof(User))]
    	public  User UserId { get {return _UserId;} set{ SetPropertyValue<User>("UserId", ref _UserId, value); } }
    
        [Association(@"WishlistsProductsReferences", typeof(Wishlist))]
    	public  XPCollection<Wishlist> DanhSachWishlists { get{{ return GetCollection<Wishlist>("DanhSachWishlists"); }} }
    
    }
}
