//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    using DevExpress.Xpo;
    using System.ComponentModel.DataAnnotations.Schema;
    using DevExpress.ExpressApp.ConditionalAppearance;
    using DevExpress.ExpressApp.Editors;
    using DevExpress.Persistent.Base;
    using DevExpress.ExpressApp.Model;
    public partial class User: XPLiteObject
    {
    	//VNB: User
        public User()
        {
            this.IsActive = true;
            //VNB disable: this.Carts = new List<Cart>();
            //VNB disable: this.Canvas = new List<Canva>();
            //VNB disable: this.Products = new List<Product>();
            //VNB disable: this.Posts = new List<Post>();
            //VNB disable: this.Wishlists = new List<Wishlist>();
        }
    
        private int _iD;
    	[DevExpress.Xpo.Key(true)]
    	[Required]
    	public int ID 
    	{ 
    		get { return _iD; } 
    		set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnIDChanged();
    			}
    		} 
    	}
    	partial void OnIDChanged(); 
    
        private string _userName;
    	public string UserName 
    	{ 
    		get { return _userName; } 
    		set
    		{
    			if (value != _userName) {
    				_userName = value;
    				 OnUserNameChanged();
    			}
    		} 
    	}
    	partial void OnUserNameChanged(); 
    
        private bool _isActive;
    	[Required]
    	public bool IsActive 
    	{ 
    		get { return _isActive; } 
    		set
    		{
    			if (value != _isActive) {
    				_isActive = value;
    				 OnIsActiveChanged();
    			}
    		} 
    	}
    	partial void OnIsActiveChanged(); 
    
        private bool _changePasswordOnFirstLogon;
    	[Required]
    	public bool ChangePasswordOnFirstLogon 
    	{ 
    		get { return _changePasswordOnFirstLogon; } 
    		set
    		{
    			if (value != _changePasswordOnFirstLogon) {
    				_changePasswordOnFirstLogon = value;
    				 OnChangePasswordOnFirstLogonChanged();
    			}
    		} 
    	}
    	partial void OnChangePasswordOnFirstLogonChanged(); 
    
        private string _storedPassword;
    	public string StoredPassword 
    	{ 
    		get { return _storedPassword; } 
    		set
    		{
    			if (value != _storedPassword) {
    				_storedPassword = value;
    				 OnStoredPasswordChanged();
    			}
    		} 
    	}
    	partial void OnStoredPasswordChanged(); 
    
    
        [Association(@"UserCartsReferences", typeof(Cart))]
    	public  XPCollection<Cart> DanhSachCarts { get{{ return GetCollection<Cart>("DanhSachCarts"); }} }
    
        [Association(@"UserCanvasReferences", typeof(Canva))]
    	public  XPCollection<Canva> DanhSachCanvas { get{{ return GetCollection<Canva>("DanhSachCanvas"); }} }
    
        [Association(@"UserProductsReferences", typeof(Product))]
    	public  XPCollection<Product> DanhSachProducts { get{{ return GetCollection<Product>("DanhSachProducts"); }} }
    
        [Association(@"UserPostsReferences", typeof(Post))]
    	public  XPCollection<Post> DanhSachPosts { get{{ return GetCollection<Post>("DanhSachPosts"); }} }
    
        [Association(@"UserWishlistsReferences", typeof(Wishlist))]
    	public  XPCollection<Wishlist> DanhSachWishlists { get{{ return GetCollection<Wishlist>("DanhSachWishlists"); }} }
    
        private Customer _CustomerId;
    	[ImmediatePostData]
    	//One to One: From 'User' to 'Customer'
    	public  Customer CustomerId { 
    		get {return _CustomerId;}
    		set{ SetPropertyValue<Customer>("CustomerId", ref _CustomerId, value); OnChanged("CustomerId"); }
    	 }
    
    }
}
