//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeclick.vn.Module.BusinessObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vnModelContainer : DbContext
    {
    	public vnModelContainer(string connectionString) 
    		: base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Product_type> Product_typeSet { get; set; }
        public virtual DbSet<Product_detail> Product_detailSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Category_type> Category_typeSet { get; set; }
        public virtual DbSet<Category_detail> Category_detailSet { get; set; }
        public virtual DbSet<Tag> TagSet { get; set; }
        public virtual DbSet<Post> PostSet { get; set; }
        public virtual DbSet<Post_detail> Post_detailSet { get; set; }
        public virtual DbSet<Department> DepartmentSet { get; set; }
        public virtual DbSet<Floor> FloorSet { get; set; }
        public virtual DbSet<Room> RoomSet { get; set; }
        public virtual DbSet<Canva> CanvaSet { get; set; }
        public virtual DbSet<Cart> CartSet { get; set; }
        public virtual DbSet<Wishlist> WishlistSet { get; set; }
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<Customer_type> Customer_typeSet { get; set; }
        public virtual DbSet<City> CitySet { get; set; }
    }
}
